sap.ui.define([
	"dbedit/model/BaseObject",
	"sap/ui/model/resource/ResourceModel"
], function(BaseObject, ResourceModel) {
	"use strict";
	return BaseObject.extend("dbedit.model.ReportModel", {

		constructor: function(data) {
			BaseObject.call(this);

			this.Inputs = {
				results:[],
				selectedRow: {},
				selectedRows:[],
				rowNarrativeCount:[],
				rowLineCount:[],
				tableData:[],
				printbillsData: {},
				printfinalData : {},
				qParms: {
					SESSION_ID: "?session_id=",
					FILTER: "?$filter=",
					JSON: "&$format=json",
					DATAJSON: "?$format=json",
					METADATA: "/$metadata",
					ACTION: "?Action=",
					ACTION2: "?ACTION=",
					DBToStatus: "/DBToStatus",
					HeaderToGroupInfo: "/HeaderToGroupInfo",
					PriceByMatnr: "/PriceByMatnr",
					value: "/$value",
					Top20: "&$top=20"

				},
				lsValues: {
					SESSION_ID: localStorage.getItem("sid"),
					USER_ID: localStorage.getItem("uid"),
					CONUMBER: "&CoNumber=",
					Buzei: "&Buzei=",
					Hours: "&Hours=",
					WBS_NODE2: "&WBS_NODE2=",
					Percentage: "&Percentage=",
					ToActivityCode: "&ToActivityCode=",
					ToFfActivityCode: "&ToFfActivityCode=",
					ToFfTaskCode: "&ToFfTaskCode=",
					ToMatter: "&ToMatter=",
					ToTaskCode: "&ToTaskCode=",
					PSPID: "&PSPID=",
					Submit: "&Submit=",
					budat_to: "&budat_to=",
					budat_from: "&budat_from=",
					Budat: "&Budat=",
					Belnr: "?Belnr=",
					Vbeln: "&Vbeln=",
					FinalVbeln: "VBELN=",
					GROUPBILL: "&GROUPBILL=",
					FKDAT: "&FKDAT=",
					FKART: "&FKART=",
					STATUS: "&STATUS=",
					TYPEOFAPPROVAL: "&TYPEOFAPPROVAL=",
					CancelVbeln: "Vbeln=",
					Posnr: "&Posnr=",
					ToVbeln: "&ToVbeln=",
					Counter: "&Counter=",
					ToPhaseCode: "&ToPhaseCode="
				},

				saveObjects: [],
				isChanged: false,
				spellCheckLogValue: 0,
				scope: {},
				"InputFields": ["Client", "Mpatner", "Pspid", "Rptgroup", "Mgbill", "Werks", "Vkorg", "Vbeln"],
				"services": {
					"InitialuserDataset": "/UserDataSet(Uname='')",
					"UpdateduserDataset": "/UserDataSet(Bname='",
					"Matter": "/Matter",
					"OrderItemSet": "/OrderItemSet",
					"CreateFinal": "CreateFinal",
					"DraftCancel": "DraftCancel",
					"MatterSet": "/MatterSet",
					"FileListSet": "/FileListSet",
					"WipMattersSet": "/WipMattersSet",
					"WipDetailsSet": "/WipDetailsSet",
					"BillSelectSet": "/BillSelectSet",
					"BillDetailSet": "/BillDetailSet",
					"PricingTypeSet": "/PricingTypeSet",
					"PriceTypeItmSet": "/PriceTypeItmSet",
					"BillSummarySet": "/BillSummarySet",
					"batchBillSummarySet": "/BillSummarySet",
					"BillEditMatterDetailSet": "/BillEditMatterDetailSet",
					"PDFOutCollection": "/PDFOutCollection",
					"DbOutputTypeSet": "/DbOutputTypeSet",
					"FbOutputTypeSet": "/FbOutputTypeSet",
					"FBMassOutputTypeSet": "/FBMassOutputTypeSet",
					"ClientByCompanyCodeSet": "/ClientsGeneralSet",
					"PaymentTermsSet": "/PaymentTermsSet",
					"Tax1InfoSet": "/Tax1InfoSet",
					"TimeKeeper": "/TimeKeeper",
					"TimeKeeperSet": "/PartnerNumberSet",
					"PartnerTypeTKSet": "/PartnerTypeSet",
					"MatterGroupBillSet": "/MatterGrpBillSet",
					"PartnerDetailSet": "/ClientPayersSet",
					"MatterReportingGroupSet": "/MatterReportingGroupSet",
					"SalesOrgSet": "/SalesOrgSet",
					"ZWerksSet": "/BillingOfficeSet",
					"OpenDbForMatterSet": "/OpenDbForMatterSet",
					"WIPTRANSFER": "/WIPTRANSFER",
					"WIPMSPLIT": "/WIPMSPLIT",
					"BILLTRANSFER": "/BillTransfer",
					"CurrencySet": "/CurrencySet",
					"TaskCodeSet": "/TaskCodeSet",
					"BillTextsSet": "/BillTextsSet",
					"ActivityCodeSet": "/ActivityCodeSet",
					"ActCodeSet": "/ActCodeSet",
					"MatterSearchSet": "/MatterSearchSet",
					"MatterPhaseSet": "/MatterPhaseSet",
					"FfTaskCodeSet": "/FfTaskCodeSet",
					"FfActivityCodeSet": "/FfActivityCodeSet",
					"CreateDraft": "CreateDraft",
					"DBCreateLogSet": "DBCreateLogSet",
					"ADDLATEWIP": "/AddLateWip",
					"ReplaceWordsSet": "/ReplaceWordsSet",
					"UserDataSet": "/UserDataSet",
					"WFCommentsSet": "/WFCommentsSet",
					"FBillMassPrint": "FBillMassPrint",
					"DBillMassPrint": "/DBillMassPrint",
					"FinalBillTypeSet": "/FinalBillTypeSet",
					"DbStatusSet": "/DbStatusSet",
					"ChangeStatus": "ChangeStatus",
					"ZprsShZzmatrptgrpWfSet": "/MatterRptGrpSet",
					"VarinatSaveSet": "/VarinatSaveSet",
					"GetLogSet": "GetLogSet",
					"lookup": {
					  "COUNTRY": "/countrylookup/"
					},
					"OfficeSet": "/BillingOfficeSet",
					"HT001Set": "/SalesOrgSet",
					"PhaseCodeSet": "/PhaseCodeSet",
					"BreGroupingSet": "/BreGroupingSet",
					"WipAmountsSet": "/WipAmountsSet",
					"billdataset": "/BillSummarySet('"

				},
				
				Toolbar: {
					CreateFinalBill: true,
					CancelDraftBill: true,
					PrintFinalBill:true,
					PrintDraftBill:true,
					ChangeStatus: true,
					Save:false,
					ReplaceWords:false,
					Reviewed:false,
					UnReviewed:false,
					GlobalSpellCheck:false,
					Reprice:false,
					AddComments:false,
					Postpone:false,
					FullWriteDown:false,
					LineItemReprice:false,
					WriteUpDown:false,
					BillExactAmount:false,
					RateOverride:false,
					UpdateCodes:false,
					Transfer:false,
					Consolidate:false,
					SplitTransfer:false,
					Undo:false
					
					
				},

				ToolbarEnable: {
					CreateFinalBill: false,
					CancelDraftBill: false,
					PrintFinalBill:false,
					PrintDraftBill:false,
					ChangeStatus: false,
					Save:false,
					ReplaceWords:false,
					Reviewed:false,
					UnReviewed:false,
					GlobalSpellCheck:false,
					Reprice:true,
					AddComments:true,
					Postpone:false,
					FullWriteDown:false,
					LineItemReprice:false,
					WriteUpDown:false,
					BillExactAmount:true,
					RateOverride:false,
					UpdateCodes:false, 
					Transfer:false,
					Consolidate:false,
					SplitTransfer:false,
					Undo:false
				},
				dicDefLanguage: "en_US"
			

			};
		}
	});
});